version: '3'

services:
  redis:
    container_name: metsenat_redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6380:6379"  # Change this line to a different host port if needed
    volumes:
      - redis:/data

  metsenat-db:
    container_name: metsenat_db
    image: postgres
    ports:
      - '5433:5432'
    env_file:
      - .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metsenat:
    image: registry.gitlab.com/nomonovjahongirbek/metsenat/develop:web
    build: ./
    container_name: metsenat_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - metsenat-db

  metsenat-worker:
    image: registry.gitlab.com/nomonovjahongirbek/metsenat/develop:web
    build: ./
    container_name: metsenat_worker
    command: celery --app=config worker -l INFO
    volumes:
      - ./:/usr/src/app/
    user: root
    restart: unless-stopped
    env_file:
      - .env.example
    depends_on:
      - metsenat-db
      - redis

volumes:
  postgres_data:
  redis:
