# Generated by Django 4.2.5 on 2023-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('legal_entity', 'Yuridik shaxs'), ('individual', 'Jismoniy shaxs')], max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('pending', 'Moderatsiyda'), ('confirmed', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=125, null=True)),
                ('payment_amount', models.BigIntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('transfer', "Pul o'tkazmalari")], max_length=50)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
