# Generated by Django 4.2.5 on 2023-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('pending', 'Moderatsiyda'), ('confirmed', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=50),
        ),
    ]
